Repository ohmyzsh/ohmyzsh, pull requests merged in 2018-09, with the labels that each got.

#3860 fasd: drop-in replacement for the autojump j alias
  plugins/fasd/fasd.plugin.zsh
Labels: alias, new

#6362 make git config oh-my-zsh.hide-status work with the agnoster theme
  themes/agnoster.zsh-theme
Labels: testers needed

#5477 git auto fetch
  plugins/git-auto-fetch/README.md
  plugins/git-auto-fetch/git-auto-fetch.plugin.zsh
Labels: git, plugin, testers needed
